/** Shared script for the tickets presentation page and the live-app teleprompter. */

export const LIVE_SCENES = [
  {
    id: "overview",
    ticket: "T2",
    sprint: "S1",
    path: "/app/tax-filings?year=2026&semester=3",
    click: "Open Compliance & Tax Filing. Do not change any card dropdown — there isn’t one.",
    say: "Status lives on the filing workflow now. Nobody can mark a modelo as filed by hand.",
  },
  {
    id: "calculate",
    ticket: "T1",
    sprint: "S1",
    path: "/app/tax-filings/calculate?year=2026&semester=3",
    click: "Click Calculate Tax, then read 130, 111, 190, and 390. Figures must match the API JSON.",
    say: "Cards now read the engine fields: irpf_payable, total_income, taxable_income, net_vat. No more €0.00 from mismatched names.",
  },
  {
    id: "vat",
    ticket: "T3",
    sprint: "S2",
    path: "/app/tax-filings/calculate?year=2026&semester=3",
    click: "On Modelo 303, point at Breakdown by Rate — 21%, 10%, 4%, 0%.",
    say: "303 now returns VAT split by rate. The breakdown only appears when the engine has those buckets.",
  },
  {
    id: "pdf",
    ticket: "T4",
    sprint: "S1",
    path: "/app/tax-filings/calculate?year=2026&semester=3",
    click: "Click the download icon on an approved 303 card. A draft PDF should open.",
    say: "Draft download is wired. Period, NIF, and the same totals as the card.",
  },
  {
    id: "cases",
    ticket: "T9",
    sprint: "S2",
    path: "/app/tax-filings/cases",
    click: "Open filings list. Mention one live filing per NIF + modelo + period.",
    say: "A second filing for the same period is refused with 409 and the existing reference. Totals lock after Approve.",
  },
  {
    id: "filing",
    ticket: "T7–T8",
    sprint: "S4",
    path: "/app/tax-filings/cases",
    click: "Open a 303 in APPROVED. Show Submit to AEAT vs Submit (test). Do not click Record accepted on 303.",
    say: "Live submit builds official XML, sends it on the modelo client, and stores AEAT code, message, and justificante. Password is typed here and never stored.",
  },
  {
    id: "certificate",
    ticket: "T6",
    sprint: "S3",
    path: "/app/settings/compliance",
    click: "Open Certificate. This .p12 is for modelo presentación — not VeriFactu invoices.",
    say: "Two pipes: invoices stay on VeriFactu. Returns use a separate AEAT modelo client with its own mTLS.",
  },
  {
    id: "invoices",
    ticket: "Guardrail",
    sprint: "S3",
    path: "/app/invoices",
    click: "Open any invoice and point at Facturae XML. That path is unchanged.",
    say: "Invoice submission still works. We did not reuse facturae_service for modelos.",
  },
];

export const SLIDES = [
  {
    id: "title",
    durationMs: 11000,
    sprint: null,
    tickets: [],
    title: "Contia365",
    kicker: "Tickets v2  ·  Spain tax filing",
    say: "This is the remaining Spain tax work, checked against the current product. Country, fiscal profile, and review-approve are already live. The gap we closed is filing a real modelo.",
  },
  {
    id: "pipeline",
    durationMs: 16000,
    sprint: null,
    tickets: [],
    title: "Where the product stands",
    say: "Select country and fiscal profile are done. Calculate and review are done. Send modelo to AEAT is now in the product, with test mode as an explicit fallback until sandbox credentials are used.",
  },
  {
    id: "s1",
    durationMs: 18000,
    sprint: "S1",
    tickets: ["T1", "T2", "T4", "T11"],
    title: "Trustworthy drafts",
    say: "Sprint one: cards show engine totals, there is no hand-set filed status, draft PDF downloads, and Italy is coming-soon with a waitlist instead of a fake tax engine.",
  },
  {
    id: "t3",
    durationMs: 14000,
    sprint: "S2",
    tickets: ["T3"],
    title: "303 VAT by rate",
    say: "The engine now returns the 21, 10, 4, and 0 split. The 303 card renders that breakdown so a demo never shows a blank VAT block.",
  },
  {
    id: "guards",
    durationMs: 16000,
    sprint: "S2",
    tickets: ["T9", "T10", "T12", "T13"],
    title: "One filing, one owner, honest waitlist",
    say: "Duplicate periods return 409. Only the owner can approve or submit. White Label and Italy waitlist rows are saved. Person and Business are the stored types — freelancer and company are aliases.",
  },
  {
    id: "xml",
    durationMs: 15000,
    sprint: "S3",
    tickets: ["T5", "T6"],
    title: "Official 303 file and AEAT client",
    say: "A dedicated 303 file service maps totals to casillas. aeat_modelo_client talks to the modelo service with its own URL and certificate. VeriFactu is untouched.",
  },
  {
    id: "submit",
    durationMs: 18000,
    sprint: "S4",
    tickets: ["T7", "T8"],
    title: "Real submit and the result panel",
    say: "From APPROVED, live submit builds XML, sends it, and stores AEAT code, message, CSV, and justificante. Rejected filings show the error and can calculate again. Test mode remains a labelled fallback.",
  },
  {
    id: "more",
    durationMs: 14000,
    sprint: "S5",
    tickets: ["T14", "T15"],
    title: "130, withholdings, monthly 303",
    say: "130 files the same way as 303. 111 and 190 need percipient lines before live send. When the profile is REDEME, 303 calculates and files month by month.",
  },
  {
    id: "close",
    durationMs: 14000,
    sprint: null,
    tickets: [],
    title: "What still needs AEAT",
    say: "Sandbox access and a year-specific schema are the remaining external blockers. Payment NRC is not in this release. Accepted by AEAT is not paid.",
  },
];
